### ISSUE TITLE
feature request: splash duration

### ISSUE THREAD

**Issue by lubi888** [henriquearthur/flutter_native_splash#10]
Olá de novo, Henrique,

How are things?

On the app i'm working on right now the splash works fine and then it disappears and there's still a 3-4 second gap between the end of the splash and when my first page loads. I tried it on a generic app, one that doesn't have a lot of info on the 1st page, and the delay between the splash and the home page is only 1-2 seconds. My app seems to be taking longer to load and so I would like to be able to draw out the splash longer in time.

I wonder if it would be possible to increase the duration of the splash screen manually? Maybe using milliseconds? Something like:

```
flutter_native_splash:
    image: assets/splash.png
    color: "#000000"
    duration: 5000
```

I'mi hoping that this would make the app start directly after the splash disappears. There may be other technical reasons why this might now work but it might work for some programmers and apps.

Just wondering, Henrique. Anyway, glad to see you're up to 79% on pub.dev as you were only 50% a few days ago. Pretty cool.

Ciao,

lubi

**Comment by henriquearthur** [comment]
Hello lubi,

I don't think adding a `duration` property is a good idea. The thing is, a splash screen is meant to be visible while the app is loading and not for a certain period of time. Let's say you specify a 5 seconds splash screen but you app loads on 10 seconds, you have a 5 seconds gap. If your app loads in 3 seconds, you have 2 seconds lost. I am not an UX expert but I'm sure those guys would say you lose a few users on those 2 seconds.

For what I understand, you have something loading on your app after Flutter itself has loaded, something like a `FutureBuilder` or `StreamBuilder` or whatever. If that's the case, then I think it would be more interesting to add a loader, progress bar or placeholder boxes while content is loading.

From the technical perspective, implementing a `duration` property would also mean adding custom `Activity` on Android and custom `ViewController` on iOS. It is not possible to do it by just using `launch_background.xml` and `LaunchScreen.storyboard`.

I would like to hear your thoughts on this before closing.

Thanks.

**Comment by lubi888** [comment]
Hi Henrique,

I think you should give options to programmers and let them figure out what works and what doesn't. There are going to be so many different types of flutter apps that it will work for some and not others. Each programmer is going to know about boot time after watching it happen scores of times. 

The duration option was what I was after but if think you could implement a progress bar or time indicator that that would also work for me and probably others. 

The point is to keep the customer engaged and entertained from the very tap launch of an app.

Its up to you, Henrique. If you don't think this is a good feature request then you may close it. I'm glad the splash works for me. However, I wouldn't close an 'Feature Request' label early as they are request from other programmers and you can leave them and come back to them after time and when you are ready or when you have some alternative ideas about them. Feature Requests sometimes help in that they can make one think outside of the box. They are a challenge which one might learn from.

Anyway, tenha um bom fim de semana, Henrique

**Comment by b-cancel** [comment]
@lubi888 If you want a duration then use this AND THEN use a programmatic load screen
https://pub.dev/packages/flutter_splash_screen does the job I believe

The reason this can't be done the way you seem to want is that splash screens by default on all platforms only show up for as long as the app is loading

So making it stay for any longer is going to just require regular old flutter code that is SEPARATE from the code required to make an actual splash screen

2 completely separate things

but I agree with @henriquearthur it's just bad UX
Even UX professionals agree this is bad practice
no user wants to be forced to wait
not even for a pretty animation

**Comment by shinriyo** [comment]
@lubi888 it is good idea. but not yet.
