### ISSUE TITLE
color code is truncated in android colors.xml

### ISSUE THREAD

**Issue by vladimirshramov** [henriquearthur/flutter_native_splash#103]
steps: 
1) pubspec.yaml:
```
flutter_native_splash:
  image: assets/images/splash.png
  color: 080582

```
2) flutter pub run flutter_native_splash:create

Actual result: res/values/colors.xml value:
` <color name="splash_color">#80582</color>`
ExpectedResult:
` <color name="splash_color">#080582</color>`

**Comment by avioli** [comment]
`color: "080582"`

**Comment by winds1983** [comment]
you can maunlly change it in res/values/colors.xml file
