### ISSUE TITLE
Background action in Splash Screen

### ISSUE THREAD

**Issue by vuhuyhieu** [henriquearthur/flutter_native_splash#105]
What if I need to run some of the background actions while the splash screen is running? For example, fetching some API, checking whether I have access token store on SharedPreferences, etc. How did I do it in my Flutter code, when I can't control Splash Screen from my Flutter code?

**Comment by avioli** [comment]
The point of the splash screen on mobile is to show up until your flutter code can finally run on its own.

If you want to "retain" it until your loading and stuff is done - just add a home screen that is exactly the same as the splash screen - an image and a background, then do whatever you want in flutter.

Good luck

**Comment by vuhuyhieu** [comment]
A screen written by Flutter will never be exactly the same as the splash screen of native code. My splash screen is simple, like you said, an image and a background with color. But I cannot adjust the image's size to be the same as a native splash screen. I tried. Not found a solution yet :/

**Comment by avioli** [comment]
@vuhuyhieu can you post a link to an image and a background colour, then a screenshot of the "native" splash screen?

**Comment by jonbhanson** [comment]
@vuhuyhieu here is example code of what @avioli described:

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: Future.delayed(Duration(seconds: 3)),
      builder: (context, AsyncSnapshot snapshot) {
        // Show splash screen while waiting for app resources to load:
        if (snapshot.connectionState == ConnectionState.waiting) {
          return MaterialApp(home: Splash());
        } else {
          // Loading is done, return the app:
          return MaterialApp(
            home: Scaffold(body: Center(child: Text('App loaded'))),
          );
        }
      },
    );
  }
}

class Splash extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Icon(
          Icons.apartment_outlined,
          size: MediaQuery.of(context).size.width * 0.785,
        ),
      ),
    );
  }
}
```
