### ISSUE TITLE
cannot build: import android.osBuild not found

### ISSUE THREAD

**Issue by michelemazzei** [henriquearthur/flutter_native_splash#107]
Projects/mypasswords/android/app/src/main/java/com/example/mywallet/MainActivity.java:11: error: class, interface, or enum expected                                                                                                                           
 import android.os.Build;                                               
 ^                                                                      
1 error                                                                 
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileDebugJavaWithJavac'.             
> Compilation failed; see the compiler error output for details.

**Comment by jonbhanson** [comment]
Should be resolved by 48981828e831768c4ad89a35475e8f9f24e0aca5.
