### ISSUE TITLE
Android - White screen instead of splash screen

### ISSUE THREAD

**Issue by Okladnoj** [henriquearthur/flutter_native_splash#108]
The previous (for **android**, **ios**) application worked fine. beautiful and fast start screen !!!)))

But I created another application (for the **desktop**) and the splash screen does not work !!! (((

**Clarification:** - does not work on either **desktop** or **Android**

I will leave a link to the repository
https://github.com/Okladnoj/test_pro_area

**Comment by jarekb123** [comment]
I faced the same issue with emulator.

What I've done - removed not changed `drawable-v21` directory.
Check that https://github.com/Okladnoj/test_pro_area/blob/master/android/app/src/main/res/drawable-v21/launch_background.xml is not changed by the plugin.

**Comment by Okladnoj** [comment]
Yes Yes Yes!!!!)))

@jarekb123 
Thank you very much!!!)) It helped me the first time !!!

The repository has been updated!)
