### ISSUE TITLE
"CantFindMainActivityPath Not able to determinate MainActivity path"

### ISSUE THREAD

**Issue by doga** [henriquearthur/flutter_native_splash#109]
Splash screen generation fails on Flutter project created with Flutter version 1.26.0-2.0.pre.64. Is flutter_native_splash still being maintained?

$ flutter pub run flutter_native_splash:create
[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[Android] Updating colors.xml with color for splash screen background
[Android] Updating styles.xml with full screen mode setting
Unhandled exception:
*** ERROR [flutter_native_splash] ***
CantFindMainActivityPath
Not able to determinate MainActivity path. Maybe the problem is your package path OR your AndroidManifest.xml 'package' attribute on manifest.
#0      _javaOrKotlin (package:flutter_native_splash/android.dart:335:5)
<asynchronous suspension>
#1      _applyMainActivityUpdate (package:flutter_native_splash/android.dart:308:27)
<asynchronous suspension>
#2      createSplash (package:flutter_native_splash/android.dart:42:3)
<asynchronous suspension>
#3      createSplash (package:flutter_native_splash/flutter_native_splash.dart:20:5)
<asynchronous suspension>
pub finished with exit code 255
$ cat pubspec.yaml
...
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
...
$ flutter doctor -v
[✓] Flutter (Channel master, 1.26.0-2.0.pre.64, on macOS 11.1 20C69 darwin-x64, locale en-CH)
    • Flutter version 1.26.0-2.0.pre.64 at /Users/da/usr/flutter
    • Framework revision 9ff4326e1f (24 hours ago), 2020-12-17 06:19:05 +0000
    • Engine revision 6edb402ee4
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/da/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/da/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • iPhone (mobile)                    • 3d25ed56e0b3522676d74b926fbb7165b2ba83fc • ios            • iOS 14.2
    • macOS (desktop)                    • macos                                    • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome                                   • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
$

**Comment by brunodmn** [comment]
Same here.
 I solved by changing package name on AndroidMainfest. 
 My package name was different than my path tree (see path where MainActivity is hosted) .

**Comment by M123-dev** [comment]
Same here

**Comment by jonbhanson** [comment]
Should be resolved by 48981828e831768c4ad89a35475e8f9f24e0aca5.
