### ISSUE TITLE
Keyboard override issue

### ISSUE THREAD

**Issue by DevangSharma** [henriquearthur/flutter_native_splash#112]
while using splash screen from this plugin app faces keyboard override issue which don't adjust the screen according to space left after keyboard.
I tried using scroll view but its not working

**Comment by jonbhanson** [comment]
What is your platform?
Do you mean that your app view should shrink to fit a smaller area when the keyboard appears?  So right now the keyboard covers part of your app?

**Comment by DevangSharma** [comment]
Yes, after using the splash screen it happens

**Comment by sksayed** [comment]
Same thing happened with me also , i have also opened a issue [issue_link](https://github.com/henriquearthur/flutter_native_splash/issues/117)

**Comment by acheronian** [comment]
Same happens to me, removing the code below in styles.xml located in android/src/main/res/values fixes this issue for me. 

` <item name="android:windowFullscreen">true</item>`

Solution and detailed issue description can be found [here](https://github.com/henriquearthur/flutter_native_splash/issues/39).

**Comment by jonbhanson** [comment]
Should be resolved by 48981828e831768c4ad89a35475e8f9f24e0aca5.
