### ISSUE TITLE
[Regression] IOS is generating a background color not consisten with the one in pubspec.yml

### ISSUE THREAD

**Issue by nerder** [henriquearthur/flutter_native_splash#115]
This code seems to be bugged since is not generate the color correctly:

https://github.com/henriquearthur/flutter_native_splash/blob/ecfa8fefe108fd9ac57e596a80c3bcf394114e7e/lib/ios.dart#L207

Example:

`#FF0024` gets translated into the following image
<img width="103" alt="image" src="https://user-images.githubusercontent.com/3502356/104079925-96129580-5225-11eb-9fdd-9a6dab7ddfdc.png">

**Comment by jonbhanson** [comment]
Thanks for the heads up!  Should be fixed now.
