### ISSUE TITLE
White screen on latest versions of Android Studio and Flutter Plugin

### ISSUE THREAD

**Issue by khalitovsv** [henriquearthur/flutter_native_splash#118]
**flutter_native_splash** does its job correctly... but when starting application its always white screen...

Steps to reproduce:

Upgrade all to latest versions.
Create new flutter project.
Folllow flutter_native_splash instructions.
Build app for android and start.
There is no any splashscreen.

**Comment by mmmcorpsvit** [comment]
try check

https://github.com/flutter/flutter/issues/46486#issuecomment-760117674

**Comment by jonbhanson** [comment]
@khalitovsv did you run `flutter pub run flutter_native_splash:create`?

If you include png file(s) in the config, did you add them to the correct path location?

I tried your steps to reproduce, but the splash screen was not white for me (unless I omitted one of the above)

**Comment by khalitovsv** [comment]
@jonbhanson yes i am...

1. File \ New \ New Flutter Project...

2. Adding in **pubspec.yaml**:
```
dev_dependencies:
  flutter_native_splash: ^0.2.5
  
flutter_native_splash:
  color: "ff0000"
```  

3. Running in terminal: 
```
C:\Development\Projects\Flutter\flutter_native_splash_test>flutter pub get
Running "flutter pub get" in flutter_native_splash_test...         367ms

C:\Development\Projects\Flutter\flutter_native_splash_test>flutter pub run flutter_native_splash:create
[Android] Updating colors.xml with color for splash screen background
[Android] Updating styles.xml with full screen mode setting
```

4. Running application expecting to see red splash screen, but its white...

As i said berfore... plugin do its job correctly... and make all need chcages inandroid res folder: [res.zip](https://github.com/henriquearthur/flutter_native_splash/files/5814574/res.zip)

**Comment by INEWSK** [comment]
Hello. 

I'm having the same problem. here is my flutter doctor 

[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19042.685], locale en)
    • Flutter version 1.25.0-8.1.pre at C:\Users\me\AppData\Local\Programs\Flutter\FlutterSDK
    • Framework revision 8f89f6505b (4 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\me\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\me\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 87.0.664.66

**Comment by khalitovsv** [comment]
i've reinstalled Android Studio, all plugins... same situation...

**Comment by jonbhanson** [comment]
@khalitovsv are you in the Flutter beta channel?

**Comment by jonbhanson** [comment]
It looks like this may be an issue in the Flutter beta channel.  Can you solve the problem by copying `launch_background.xml` from the `android/app/src/main/res/drawable` folder to `android/app/src/main/res/drawable-v21` folder?

**Comment by khalitovsv** [comment]
@jonbhanson yes, thank you! switched to stable channel, problem has gone!
