### ISSUE TITLE
Feature Request: Allow full-screen to be disabled

### ISSUE THREAD

**Issue by yaymalaga** [henriquearthur/flutter_native_splash#14]
This would be a really nice feature to have as a flag. Furthermore, in Android at least, it would be also good to be able to pick the statusbar color in case it is shown.

**Comment by henriquearthur** [comment]
Thanks for your feedback, disabling full screen on Android is now available on **v0.1.8+1**.

You can use:
```yaml
android_disable_fullscreen: true
```
---
On Material spec, status bar color is always related to the splash screen background (https://material.io/design/communication/launch-screen.html and https://material.io/design/color)

A PR (https://github.com/henriquearthur/flutter_native_splash/pull/16) which uses Material specs to generate status bar color was just merged and it is also available in **v0.1.8+1**. 

Customizing status bar color would be against Material Design specs and I don't think that is a good idea. Feel free to open a new issue for that if you have a use-case or a strong reason it should be 
customizable.
