### ISSUE TITLE
[iOS] Status bar doesn't hide in landscape

### ISSUE THREAD

**Issue by joaowd** [henriquearthur/flutter_native_splash#15]
This only happens on a **physical** devices.

I created a new flutter project and after installing this package the status bar doesn't hide in landscape mode.

In portrait the status bar appears (like it should).

**Comment by joaowd** [comment]
Any news on this @henriquearthur ? Did you found the same problem ?

**Comment by henriquearthur** [comment]
Thanks for reporting and sorry it took a while for me to get to this.

I can't reproduce this on an emulator and I can't test on a real device.

Testing on an emulator, both portrait and landscape, I can see the status bar is initially hidden and it appears 1~2 seconds before app loads.

As you said this only happens on physical devices, I am not sure what to look for _(I am not an iOS developer)_

Did you manually modify `LaunchScreen.storyboard` or `Info.plist`?

This is **Deployment info** after package ran:
![image](https://user-images.githubusercontent.com/5016325/64995524-dc661780-d8b1-11e9-94ad-0e88833b8ac6.png)

**Comment by joaowd** [comment]
I didn't modify those files, I also have a checkmark in the hide status bar

**Comment by joaowd** [comment]
Removing this from Info.plist:

```
	<key>UIStatusBarHidden</key>
	<true/>
```

Fixed my problem.

**Comment by henriquearthur** [comment]
> Fixed my problem by removing this from Info.plist:
> 
> ```
> <key>UIStatusBarHidden</key>
> <true/>
> ```

That will show the status bar on both landscape and portrait. Is that intended behaviour?

**Comment by joaowd** [comment]
No, the intention is to hide in landscape. That’s the weird part, but it works!
