### ISSUE TITLE
Creation fails due to code which is written multiple times in MainActivity.kt

### ISSUE THREAD

**Issue by Xentraxx** [henriquearthur/flutter_native_splash#19]
Some initialization of variables are added even though they exist already.
Even if I delete those lines and resolve the build errors, the image appears too big on my emulator. Even after a clean and rebuild.

e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (8, 19): Conflicting import, imported name 'Build' is ambiguous
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (9, 21): Conflicting import, imported name 'ViewTreeObserver' is ambiguous
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (10, 21): Conflicting import, imported name 'WindowManager' is ambiguous
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (12, 19): Conflicting import, imported name 'Build' is ambiguous
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (13, 21): Conflicting import, imported name 'ViewTreeObserver' is ambiguous
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (14, 21): Conflicting import, imported name 'WindowManager' is ambiguous
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (19, 9): Conflicting declarations: val flutter_native_splash: Boolean, val flutter_native_splash: Boolean
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (20, 9): Conflicting declarations: var originalStatusBarColor: Int, var originalStatusBarColor: Int
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (25, 9): Conflicting declarations: val originalStatusBarColorFinal: Int, val originalStatusBarColorFinal: Int
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (27, 9): Conflicting declarations: val flutter_native_splash: Boolean, val flutter_native_splash: Boolean
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (28, 9): Conflicting declarations: var originalStatusBarColor: Int, var originalStatusBarColor: Int
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (33, 9): Conflicting declarations: val originalStatusBarColorFinal: Int, val originalStatusBarColorFinal: Int
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (36, 9): Conflicting declarations: val vto: ViewTreeObserver!, val vto: ViewTreeObserver!
e: C:\Users\Gaming PC\Desktop\LinkYouProjectfiles\LinkYou\android\app\src\main\kotlin\de\linkyouapp\linkyou\MainActivity.kt: (47, 9): Conflicting declarations: val vto: ViewTreeObserver!, val vto: ViewTreeObserver!

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by da-revo** [comment]
same for me

**Comment by henriquearthur** [comment]
Thanks for reporting.

Version **0.1.8+1** was looking for the wrong variable on `MainActivity` to determine if the file should be updated. 

This is now **fixed in 0.1.8+2** by looking for the correct variable .(53e6b55e49d558476207804f48c73fb8b7a86a06)

Please update the package, remove the duplicated code on `MainActivity` (this package doesn't have a remove option) and run again.

```yaml
dev_dependencies:
  flutter_native_splash: ^0.1.8+2
```

```
flutter pub pub run flutter_native_splash:create
```

Below is the original `MainActivity` created by `flutter create test` for reference:

**Java**

```java
package com.example.test;
import android.os.Bundle;
import io.flutter.app.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}

```

**Kotlin**
```kotlin
package com.example.test

import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}

```

**Comment by henriquearthur** [comment]
@Xentraxx as for image size, it is not related to this duplicated code issue.

There is a feature request issue for custom image size (https://github.com/henriquearthur/flutter_native_splash/issues/11).

While custom image size is not yet implemented, I recommend you resize your image to better fit your needs. What are the dimensions of the image?

**Comment by da-revo** [comment]
@henriquearthur works like a charm now. Appreciate the hard work. <3

**Comment by Xentraxx** [comment]
Thank you for the fast fix! Keep up the great work! I just changed the image size and now it works alright.
