### ISSUE TITLE
pub finished with exit code 255 in version 0.1.8+2

### ISSUE THREAD

**Issue by MoSala7** [henriquearthur/flutter_native_splash#20]
Hello, i've followed the guide and i met this problem !!
tried many different versions and the same problem too

`flutter pub pub run flutter_native_splash:create
[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[Android] Updating colors.xml with color for splash screen background
[Android] Updating styles.xml with full screen mode setting
Unhandled exception:
*** ERROR [flutter_native_splash] ***
CantFindMainActivityPath
Not able to determinate MainActivity path. Maybe the problem is your package path OR your AndroidManifest.xml 'package' attribute on manifest.
#0      _javaOrKotlin (package:flutter_native_splash/android.dart:315:5)
<asynchronous suspension>
#1      _applyMainActivityUpdate (package:flutter_native_splash/android.dart:288:33)
<asynchronous suspension>
#2      createSplash (package:flutter_native_splash/android.dart:39:9)
<asynchronous suspension>
#3      createSplash (package:flutter_native_splash/flutter_native_splash.dart:20:11)
<asynchronous suspension>
#4      main (file:///C:/Users/midos/AppData/Local/flutter/.pub-cache/bin/hosted/pub.dartlang.org/flutter_native_splash-0.1.8+2/bin/create.dart:5:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
pub finished with exit code 255`

**Comment by henriquearthur** [comment]
The package can't find your `MainActivity` file. It looks for it using package path on `AndroidManifest.xml`.

Can you provide the path for your `MainActivity.java` or `MainActivity.kt` and the contents of `AndroidManifest.xml`?

**Comment by MoSala7** [comment]
MainActivity.java Path:
android\app\src\main\java\com\example\child_iq\MainActivity.java

AndroidManifest.xml Content:
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.fahad.childiq">

    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="ابنك اذكى مما تتوقع"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>

**Comment by henriquearthur** [comment]
Is that the full content of `AndroidManifest.xml`?

The first line should be

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.example">
```

Please check if your file has that line.

This package looks for `package` attribute on `manifest` tag above so it can determine where is `MainActivity` located.

By the path you provided, your `package` should be `com.example.child_iq`. If it has any other value that's why the package can't find `MainActivity`.

Did you manually modify `AndroidManifest.xml` or package name on your project?

**Comment by falcaoaugustos** [comment]
It's my `AndroidManifest.xml` and yes, I've updated the package name on my project.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.beakyn.aloc">

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Aloc"
        android:icon="@mipmap/launcher_icon">
        <!-- Add the following entry, with your API key -->
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
```

**Comment by henriquearthur** [comment]
@falcaoaugustos based on `package` attribute from `manifest` tag, this package is looking for MainActivity in following paths:

**If you use Java**
`android/app/src/main/java/com/beakyn/aloc/MainActivity.java` 

**If you use Kotlin**
`android/app/src/main/kotlin/com/beakyn/aloc/MainActivity.kt`

1. Can you confirm MainActivity location is correct?
2. Please provide the output of `flutter pub pub run flutter_native_splash:create`

**Comment by falcaoaugustos** [comment]
1. My location wasn't correct. It was:
`android/app/src/main/java/com/example/aloc/MainActivity.java`
Updating it to the mentioned path make it work. Thanks.

**Comment by henriquearthur** [comment]
Closing this since OP didn't reply in a while.

This is related to MainActivity path, original path or `package` tag was probably modified.

Feel free to reopen if you still have issues @MoSala7

**Comment by sagarvd01** [comment]
I had the same issue, I created project using `flutter create --org com.example examplepro` and later edited package name in android manifest and main activity to `com.example.example.pro`. However I forgot to move main activity file from `android/app/src/main/kotlin/com/example/examplepro`. I resolved it by moving the file to `android/app/src/main/kotlin/com/example/example/pro`

If anybody edit the package name later, don't forget to edit the folder structure too.

**Comment by yenerorer** [comment]
This probably happens when you change your app name but you didn't move your MainActivity in right folder. 
Move your MainActivity to folder. 

package com.[domain].[app_name]

android\app\src\main\kotlin\com\[domain]\[app_name]\MainActivity.kt
