### ISSUE TITLE
Message appears after splash ends

### ISSUE THREAD

**Issue by aleffabricio** [henriquearthur/flutter_native_splash#21]
Hello all right, congratulations on the library, it really makes it easier, after the splash is over, a message pops up on my terminal several times

>  "Failed to send request: {" jsonrpc ":" 2.0 "," id ":" 20016 ", "method": "getVM", "params": {}} "

 what could it be? The splash works, but this message appears repeatedly.

I am using the version: 

> dependencies:
>   flutter_native_splash: ^0.1.8+2

The message happens on iOS and Android.

**Comment by henriquearthur** [comment]
Hey!

I don't think this error message is related to `flutter_native_splash`. This package only adds code for managing splash screen XML and hide/show status bar, there is nothing about JSON or RPC.

1. If you are using any code related to JSON or RPC the error is probably coming from there. Does it show a stacktrace?
2. Does this happen in a new project with `flutter create`?

**Comment by henriquearthur** [comment]
And as a suggestion you can add `flutter_native_splash: ^0.1.8+2` to your `dev_dependencies` instead of `dependencies`. This way the package will not go into your APK (it shouldn't because it's not needed there).

This is not related to your issue, just a suggestion to improve your project!

**Comment by aleffabricio** [comment]
Hello good night, the problem was in my Android Studio, because I had created a project from scratch and was giving this error after adding the library, but I reinstalled Android Studio and it worked, thanks for the support.
