### ISSUE TITLE
Cannot crash native splash with just color

### ISSUE THREAD

**Issue by anticafe** [henriquearthur/flutter_native_splash#26]
I only need to make native splash with color (without image):
```
flutter_native_splash:
  color: ffffff
```
But receive this error:
```
*** ERROR [flutter_native_splash] ***
InvalidConfigException
Your `flutter_native_splash` section does not contain a `image`.
```

I don't see any reason to require `image` in native splash - it could be optional. Could you fix it? Thanks.

**Comment by henriquearthur** [comment]
Indeed `image` should be optional in case we just want colored splash screens.

Added this in **v0.1.9**. You can just remove `image` parameter and use it like in your example

```
flutter_native_splash:
  color: "000000"
```

Don't forget to update:

```
dev_dependencies:
  flutter_native_splash: ^0.1.9
```
