### ISSUE TITLE
Strange error 'Uint32' not found

### ISSUE THREAD

**Issue by zenkog** [henriquearthur/flutter_native_splash#29]
Strange Error when doing flutter pub pub run flutter_native_splash:create
I suspect is it because the dependancies in pub.flutter-io.cn are not updated?

Failed to precompile flutter_native_splash:create:
/Users/ZK/.pub-cache/hosted/pub.flutter-io.cn/image-2.1.4/lib/src/image.dart:534:31: Error: Type 'Uint32' not found.
  void setPixel(int x, int y, Uint32 color) {
                                           ^^^^^^
/Users/ZK/.pub-cache/hosted/pub.flutter-io.cn/image-2.1.4/lib/src/image.dart:534:31: Error: 'Uint32' isn't a type.
  void setPixel(int x, int y, Uint32 color) {
                                          ^^^^^^
pub finished with exit code 1

Here is my Flutter Doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.6 18G95, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (3 available)

• No issues found!

**Comment by henriquearthur** [comment]
The error is coming from [image](https://github.com/brendan-duncan/image) package. I didn't find any issue related to this error on their repo.

I recommend doing a `flutter clean`, upgrade your dependencies and try again.

Can you share your `pubspec.yaml` file?

With more info I can open an issue on image repo.
