### ISSUE TITLE
pub finished with exit code 255

### ISSUE THREAD

**Issue by lubi888** [henriquearthur/flutter_native_splash#3]
Hi,

Just saw your link on reddit and wanted to give it a try.

Here's the error code:
`flutter pub pub run flutter_native_splash:create
[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, height and color
Unhandled exception:
RangeError: Invalid value: Only valid value is 0: -1
#0      List.insert (dart:core-patch/growable_array.dart:11:7)
#1      _updateLaunchBackgroundFileWithImagePath (package:flutter_native_splash/android.dart:104:11)
<asynchronous suspension>
#2      _applyLaunchBackgroundXml (package:flutter_native_splash/android.dart:77:12)
#3      createSplash (package:flutter_native_splash/android.dart:26:9)
<asynchronous suspension>
#4      createSplash (package:flutter_native_splash/flutter_native_splash.dart:18:5)
#5      main (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.1.4/bin/create.dart:5:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
pub finished with exit code 255`

**Comment by lubi888** [comment]
I can add some details as it looks like most of the programming worked. I'll list what was changed here. I'm using Win 10.

There are 5 new resources in app/src/main/res alongside the normal 'mipmap-hdpi', etc. and these are 'drawable-hdpi', 'drawable-mdpi' etc.

drawable\launch_background.xml has been deleted
res\values\colors.xml has been created and is clean.
res\values\styles.xml has been deleted and not written to. This is an error.

ios\Runner\AppDelegate.m has been deleted. Another error?
ios\Runner\Info.plist has been deleted. ?
it looks like all the assets of 2x and 3 x were added correctly to ios

ok, let me know if I can help in any way.

**Comment by lubi888** [comment]
Hi Henrique,

Having fun publishing?!

Here’s the contents of drawable.xml  that was deleted yesterday by the release version.

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Modify this file to customize your launch splash screen -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
<item android:drawable="@android:color/white" />

<!-- You can insert your own image assets here -->
<!-- <item>
<bitmap
android:gravity="center"
android:src="@mipmap/launch_image" />
</item> -->
</layer-list>
```

I created this flutter app recently using Android Studio because I had to upgrade my whole flutter project to AndroidX. I didn’t use the ‘flutter create’ command to create this app.  

I have check this again and just created a new flutter app using Android and the output is the same as what I already have and is shown above. Thus, there is no line you referred to `android:src="@drawable/splash`

I have just created a sample app using ‘flutter create’ and the output is the same as using Android Studio. 

Ok, I’ve just installed your updated code and here are the results for 0.1.6

```
flutter pub pub run flutter_native_splash:create

[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[Android] No colors.xml file found in your Android project
[Android] Creating colors.xml file and adding it to your Android project
[Android] Updating styles.xml with full screen mode setting
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, height and color
[iOS] Updating Info.plist for status bar hidden/visible
[iOS] Updating AppDelegate for status bar hidden/visible
```

The process took about 30 seconds to create all the files correctly. The good news is that all is working now :-)
Here’s a shot from GitHub desktop that shows how launch_background.xml was added to.
<img width="526" alt="Annotation 2019-08-27 122846" src="https://user-images.githubusercontent.com/4474859/63769352-81508e80-c8ca-11e9-9988-7b2e42d212a3.png">

Should I say ‘merci’ or ‘obrigado’ Henrique? Thanks. Plugin is working now and I find it easier to use than the other splash plugins.

**Comment by adenilson-santos** [comment]
In my case the problem was that I had changed the package name com.example for com.mydomain and forget of change already the android path name.

 If that is you case too try change here like that: 
**android/app/src/main/com/<change here 'example' for your domain>/...**

**Comment by joaovirgili** [comment]
My package: com.geekbusinesslab.PepsRelatorios. 
My MainActivity path is android/app/src/main/kotlin/com/example/pepsfield_relatorios_app/MainActivity.kt

what should i do?

**Comment by corymalcolmtaylor** [comment]
Have you tried renaming the folder to android/app/src/main/kotlin/com/**geekbusinesslab**/pepsfield_relatorios_app/MainActivity.kt

I dd that and now the create command completes and the launch image works on my android emulator.  However it still does not show up on my ios simulator (iphone SE 2nd gen).  I just  see a black screen until my app shows up.

Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d3ed9ec945 (2 weeks ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

**Comment by kunjmehta-123** [comment]
C:\flutterApps\newsplash>flutter pub pub run flutter_native_splash:create
[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[Android] No colors.xml file found in your Android project
[Android] Creating colors.xml file and adding it to your Android project
[Android] Updating styles.xml with full screen mode setting
Unhandled exception:
FormatException: Invalid radix-16 number (at character 1)
“4
^

#0      int._throwFormatException (dart:core-patch/integers_patch.dart:131:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:142:16)
#2      int._parse (dart:core-patch/integers_patch.dart:100:12)
#3      int.parse (dart:core-patch/integers_patch.dart:63:12)
#4      new HexColor (package:color/hex_color.dart:21:17)
#5      _generatePrimaryColorDarkFromColor (package:flutter_native_splash/android.dart:48:45)
#6      createSplash (package:flutter_native_splash/android.dart:42:34)
<asynchronous suspension>
#7      createSplash (package:flutter_native_splash/flutter_native_splash.dart:20:11)
<asynchronous suspension>
#8      main (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.1.9/bin/create.dart:5:3)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
pub finished with exit code 255

This is the error I'm getting. Anything I can do about this?

**Comment by lukepighetti** [comment]
My package name is `twic.app`, how can I proceed?

**Comment by s99chandra** [comment]
PS D:\flutter_projects\production\on_demand_customer> flutter pub run flutter_native_splash:create
[Android] Creating splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android]  - android/app/src/main/res/values/styles.xml
[iOS] Creating images
[iOS] Updating LaunchScreen.storyboard with width, and height
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
Unhandled exception:
XmlParserException: Expected </string>, but found </dict> at 65:1
#0      XmlGrammarDefinition.element.<anonymous closure> (package:xml/src/xml/grammar.dart:105:13)
#1      MapParser.parseOn (package:petitparser/src/parser/action/map.dart:38:37)
#2      ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#3      PossessiveRepeatingParser.parseOn (package:petitparser/src/parser/repeater/possessive.dart:67:31) 
#4      SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#5      ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#6      SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#7      MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#8      ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#9      PossessiveRepeatingParser.parseOn (package:petitparser/src/parser/repeater/possessive.dart:67:31) 
#10     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#11     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#12     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#13     MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#14     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#15     PossessiveRepeatingParser.parseOn (package:petitparser/src/parser/repeater/possessive.dart:67:31) 
#16     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#17     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#18     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#19     MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#20     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#21     PossessiveRepeatingParser.parseOn (package:petitparser/src/parser/repeater/possessive.dart:67:31) 
#22     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#23     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#24     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#25     MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#26     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#27     PossessiveRepeatingParser.parseOn (package:petitparser/src/parser/repeater/possessive.dart:67:31) 
#28     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#29     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#30     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#31     MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#32     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#33     MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#34     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#35     PickParser.parseOn (package:petitparser/src/parser/action/pick.dart:26:29)
#36     CastParser.parseOn (package:petitparser/src/parser/action/cast.dart:17:29)
#37     Parser.parse (package:petitparser/src/core/parser.dart:51:36)
#43     createSplash (package:flutter_native_splash/cli_commands.dart:23:3)
#44     main.<anonymous closure> (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.1.5/bin/create.dart:6:49)
#45     Parser.parse.<anonymous closure> (package:args/src/parser.dart:106:15)
#46     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#47     MapView.forEach (dart:collection/maps.dart:342:10)
#48     Parser.parse (package:args/src/parser.dart:95:22)
#49     ArgParser.parse (package:args/src/arg_parser.dart:335:42)
#50     main (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.1.5/bin/create.dart:7:10)
#51     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)     
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

This is the error I'm stuck in there.  how can solve this and can't understand where are error
