### ISSUE TITLE
Splash Screen image is always stretched out 

### ISSUE THREAD

**Issue by skystar7** [henriquearthur/flutter_native_splash#32]
The Splash Screen image is always stretched out no matter what resolution I use, Even using the image in the example I still get the same result:
[https://ibb.co/3yQv9SJ](https://ibb.co/3yQv9SJ)

My config:
`flutter_native_splash:
  image: assets/images/splash.png
  color: "#42a5f5"`

Thank you in advance for your help

**Comment by henriquearthur** [comment]
Is this happening on a real device or emulator? What is the screen resolution?

**Comment by skystar7** [comment]
> Is this happening on a real device or emulator? What is the screen resolution?

Real device Huawei nova 3i @ resolution 1080 x 2340 pixels

**Comment by skystar7** [comment]
Problem fixed after upgrading the project into AndroidX and used the latest flutter SDK
