### ISSUE TITLE
Can we control splash screen loading time ?

### ISSUE THREAD

**Issue by tjclubby** [henriquearthur/flutter_native_splash#36]
Can we extend the time of flash screen

**Comment by henriquearthur** [comment]
Duplicated #10 
> I don't think adding a duration property is a good idea. The thing is, a splash screen is meant to be visible while the app is loading and not for a certain period of time. Let's say you specify a 5 seconds splash screen but you app loads on 10 seconds, you have a 5 seconds gap. If your app loads in 3 seconds, you have 2 seconds lost. I am not an UX expert but I'm sure those guys would say you lose a few users on those 2 seconds.
> 
> From the technical perspective, implementing a duration property would also mean adding custom Activity on Android and custom ViewController on iOS. It is not possible to do it by just using launch_background.xml and LaunchScreen.storyboard.
