### ISSUE TITLE
how to increase splash screen display time?

### ISSUE THREAD

**Issue by dhsont** [henriquearthur/flutter_native_splash#38]
HI thanks for nice package,
I want to increase splash display time to 5 seconds or more, How to do that ?

Is it possible with this package?

**Comment by abdulllrashid** [comment]
This plugin isn't showing a screen for some time.The screen shows until the app is loaded by native os

**Comment by hardypatel30** [comment]
But  can  this wont be splash screen idea. It is just we  are replacing that white screen provided by flutter bydefault.

**Comment by henriquearthur** [comment]
Duplicated #10 
> I don't think adding a duration property is a good idea. The thing is, a splash screen is meant to be visible while the app is loading and not for a certain period of time. Let's say you specify a 5 seconds splash screen but you app loads on 10 seconds, you have a 5 seconds gap. If your app loads in 3 seconds, you have 2 seconds lost. I am not an UX expert but I'm sure those guys would say you lose a few users on those 2 seconds.
> 
> From the technical perspective, implementing a duration property would also mean adding custom Activity on Android and custom ViewController on iOS. It is not possible to do it by just using launch_background.xml and LaunchScreen.storyboard.
