### ISSUE TITLE
2 entries in launch_background.xml

### ISSUE THREAD

**Issue by htsnet** [henriquearthur/flutter_native_splash#4]
Before I run this package, I already <item> tag in my launch_background.xml file.

After the run, I see 2 item in the file:

<item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/ic_launcher" />
    </item>
    <item>
        <bitmap android:gravity="center" android:src="@drawable/splash" />
    </item>

**Comment by henriquearthur** [comment]
@htsnet can you provide more information to this issue?

**Comment by htsnet** [comment]
Sorry @henriquearthur , I didn´t see your first comment.

Before I had used this plugin, I already have a ITEM tag, like this:

`<item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/ic_launcher" />
    </item>`


Then, I run the plugin and, inside the launch_background.xml I saw the first one and this other:

`<item>
        <bitmap android:gravity="center" android:src="@drawable/splash" />
    </item>`

When the app start, I saw a mess (2 images). Then I look for the issue and found this duplilcate entry.

It is not a big deal, I just remove the first one and everything is OK.

**Comment by henriquearthur** [comment]
The `item` this package looks for is `android:src="@drawable/splash"` to check if a entry was already added. As you had a `android:src="@mipmap/ic_launcher"` `item`, the package did not detected it.

This is normal because even using the package you are free to customize `launch_background.xml` manually.

**Comment by h2jose** [comment]
> Sorry @henriquearthur , I didn´t see your first comment.
> 
> Before I had used this plugin, I already have a ITEM tag, like this:
> 
> `<item> <bitmap android:gravity="center" android:src="@mipmap/ic_launcher" /> </item>`
> 
> Then, I run the plugin and, inside the launch_background.xml I saw the first one and this other:
> 
> `<item> <bitmap android:gravity="center" android:src="@drawable/splash" /> </item>`
> 
> When the app start, I saw a mess (2 images). Then I look for the issue and found this duplilcate entry.
> 
> It is not a big deal, I just remove the first one and everything is OK.

This works for me, thanks
