### ISSUE TITLE
Multiple UIStatusBarHidden keys added to Info.plist

### ISSUE THREAD

**Issue by rrarey02** [henriquearthur/flutter_native_splash#5]
Just tried out this package and noticed that after running it, I have 3 of the following entries in my Info.plist file:

```
<key>UIStatusBarHidden</key>
<true/>
```

The package seems to be adding one of these entries to every `<dict>` element it finds, instead of just the top-level `<dict>`. My Info.plist has a few `<key>` entries with values that are `<dict>` elements, so duplicates were created.

**Comment by henriquearthur** [comment]
Fixed in **v0.1.7** (0228c5bdb10cd5b0371f183d5d83a9a652cd5e3a):
```
dev_dependencies:
  flutter_native_splash: ^0.1.7
```

---

The package looks now only for the last `</dict>` (top-level) on `Info.plist` and adds `UIStatusBarHidden` key before `</dict>`.
