### ISSUE TITLE
Conditional Splash Screen

### ISSUE THREAD

**Issue by volkankahraman** [henriquearthur/flutter_native_splash#50]
Hey, since yaml files does'nt support if condition. How can I implement conditional splash screen to my app ? For example I want to display color on intro screen when application first run. Then I want to display image as splash screen.

**Comment by henriquearthur** [comment]
The splash screen this package creates is the one provided by `launch_background.xml` on Android, which is a basic splash screen, it does not support conditions or anything similar.

I recommend creating a simple splash screen with this package, maybe an icon or just a color and then you can build your conditional splash screens with Flutter code as being your first screen.
