### ISSUE TITLE
my app become in fullscreen

### ISSUE THREAD

**Issue by yase-hesham** [henriquearthur/flutter_native_splash#51]
Hello 
First thanks for this awesome pub <3 but im facing a little problem here after using this pub , all my app become in full screen , is there any solution ? 

`flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"
  fill: false
  android_disable_fullscreen: true
  ios_disable_fullscreen: true`

**Comment by henriquearthur** [comment]
Remove the `<item name="android:windowFullscreen">true</item>` line in `styles.xml` and check if it works.

Possible duplicate: #40 and #39 

> This package changes your app to full screen mode for better splash screen experience. When the splash screen finished, full screen mode is removed. That happens in MainActivity.kt.
> 
> The problem is that the latest version of Flutter changed the default MainActivity.kt file, which means this package can't find a reference line to insert code before and after it - and because of that full screen mode is not removed.

**Comment by yase-hesham** [comment]
it works thank you
