### ISSUE TITLE
Is there a way to uninstall the splash

### ISSUE THREAD

**Issue by skystar7** [henriquearthur/flutter_native_splash#55]
Is there a way to un-modify  launch_background.xml, styles.xml and MainActivity files on Android and LaunchScreen.storyboard, Info.plist, and AppDelegate on iOS.

**Comment by IoanaAlexandru** [comment]
If you added the splash screen in a single commit, I suppose you could just revert the commit.

**Comment by jonbhanson** [comment]
Follow [97] for resolution.
