### ISSUE TITLE
Hidden status bar

### ISSUE THREAD

**Issue by YusufIslamAnwar** [henriquearthur/flutter_native_splash#60]
Unfortunately, the status bar is hidden and after the splash screen finishes, I see a black screen and I have no idea why that is happening.

**Comment by yTek** [comment]
I resolved this by removing the line :
`<item name="android:windowFullscreen">true</item>`
in the file android/app/src/main/res/values/styles.xml.

I tried to add the parameter 'android_disable_fullscreen: true' in my yaml file but it didnt erased this line.
Hope it helps 😃

**Comment by YusufIslamAnwar** [comment]
It works, thanks :).

**Comment by kleviss** [comment]
It works. I had this problem after implementing the flutter native splash screen and this solved my problem. Thanks :))
