### ISSUE TITLE
android_disable_fullscreen: true does not work

### ISSUE THREAD

**Issue by EliuTimana** [henriquearthur/flutter_native_splash#62]
Hi, when I ran `flutter pub pub run flutter_native_splash:create` for the first time it generated the files correctly, but the app ran in fullscreen mode, I changed `android_disable_fullscreen` to `true` and run the above command and nothing happened, I had to manually remove the fullscreen tag in `styles.xml` and it works.
This is the command output, but the styles file keeps unchanged.
```
flutter pub pub run flutter_native_splash:create
[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[Android] Updating colors.xml with color for splash screen background
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, height and color

```

**Comment by Chralu** [comment]
Hi @EliuTimana,

more information about `android_disable_fullscreen` behavior :

The plugin is currently unable to remove the`<item name="android:windowFullscreen">true</item>` line.

So, if it is already present in `styles.xml`, you will have to delete it manually.

**Comment by EliuTimana** [comment]
Thanks for the explanation 😄 , I'm closing this.
