### ISSUE TITLE
Splash Screen Issue

### ISSUE THREAD

**Issue by praveenprabhu1718** [henriquearthur/flutter_native_splash#64]
I added a splash screen to my flutter app using a flutter_native_splash package. Now I want to remove that splash screen but I couldn't. Even I tried to remove the package from the pubspec.yaml and the image used for splash screen from the assets directory but still the app has the splash screen. Please tell me how can I remove that? And there is a black screen that occurs between the splash screen and the home screen.

**Comment by deandreamatias** [comment]
This package, generate a code for Android and iOS. So, if you need remove the splash screen, you need remove this code from Android and iOS files. You can search in your commits and undo this changes.
However, the remove from a command line, is a nice feature for this package

**Comment by deandreamatias** [comment]
Duplicate #55

**Comment by praveenprabhu1718** [comment]
> This package, generate a code for Android and iOS. So, if you need remove the splash screen, you need remove this code from Android and iOS files. You can search in your commits and undo this changes.
> However, the remove from a command line, is a nice feature for this package

What is the command to remove it from command line?

**Comment by rakib205** [comment]
@deandreamatias,  What is the command line then?

**Comment by deandreamatias** [comment]
Never has a command line. I wanted to say:
It would be a nice feature for this package

**Comment by jonbhanson** [comment]
Follow [97](https://github.com/henriquearthur/flutter_native_splash/issues/97) for resolution.

**Comment by deandreamatias** [comment]
I think the issue closes when the merge is done
