### ISSUE TITLE
please add better explanation about android_disable_fullscreen

### ISSUE THREAD

**Issue by hiwa-jalal** [henriquearthur/flutter_native_splash#67]
i used this package and it worked fine, but then suddenly my app became un-scrollable and the keyboard was covering the `TextField`, i spent hours trying every solution available online and nothing worked until i came across a guy with the same problem that said you may have `<item name="android:windowFullscreen">true</item>` in `styles.xml` but i didn't thought of that because i never touched that file, then i opened the file and it was inside it, i removed it and finally everything went back to normal, i know you guys provide the option to disable the full screen but at least explain the consequences of making it full screen, or at least make it false by default so no one else go through my problem and miss around with all of his layout for hours, thanks.

**Comment by abbas-25** [comment]
I agree with the OP here. Same thing happened with me.

**Comment by dickverweij** [comment]
Me too, Took me a quite while to figure it out..

**Comment by jonbhanson** [comment]
Should be resolved by 48981828e831768c4ad89a35475e8f9f24e0aca5.
