### ISSUE TITLE
Image streched if source image has not same aspect ratio as device

### ISSUE THREAD

**Issue by Tonne-TM** [henriquearthur/flutter_native_splash#68]
When starting an app on a tablet in landscape mode the splashscreen will look weired. 

Could you add the funtionality to a custom picture for landscape more or something similar to adress this issue?

**Comment by deandreamatias** [comment]
Do you can add any image with this issue please?

**Comment by Tonne-TM** [comment]
I had to **pixelate** it, but you can probably get the idea. On the left site is the source image which i just to generate the splash screens. 

(Source image is 960*1600px)

![image](https://i.gyazo.com/7575ef6239409f64df6464d85f435961.png)

**Comment by deandreamatias** [comment]
You tried in real devices or other simulate devices (no tablets) ?
In other way, you tried with minor images? Like 500x500

**Comment by Tonne-TM** [comment]
Yes i tried different simulated devices. The image looks always streched when the aspect ratio is no the same as the origin image.

I tried a picture with 500*500 but still it was streched.

Is there some way to disable strech and just fill the rest of the splashscreen with a certain color (in my case white)?

**Comment by Tonne-TM** [comment]
The problem can be fixed by changing the generated code in launch_background.xml

**Add android:gravity="center"**


```xml
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/splash_color" />
    <item>
        <bitmap android:src="@drawable/splash"
                android:gravity="center"/> <!-- !!! add this line !!! -->
    </item>

</layer-list>
```

**Comment by Amerr** [comment]
> ```
> android:gravity="center"
> ```

Thanks, it worked. it should be added in the documenation

**Comment by jonbhanson** [comment]
This can be changed in the package by setting the `fill` parameter to `true` or `false`.
