### ISSUE TITLE
Missing imports from MainActivity

### ISSUE THREAD

**Issue by reducedcarpet** [henriquearthur/flutter_native_splash#7]
I did all the steps from the wee tutorial on pub.dev / readme.md but I got some big complaints from gradle (building for android obviously) that stopped the build. A tiny amount of googling later and I had to add two imports to MainActivity: 

import android.view.ViewTreeObserver;
import android.view.WindowManager;

Shouldn't this have happened automatically? Is this some unique aspect of my build? I am doing some MultiDex shenanigans so I don't know if that has affected it. Sorry this bug report is absolute grabage in terms of detail, but I thought you should know.

**Comment by henriquearthur** [comment]
Those two imports are added to MainActivity when you run the package. The package looks for the line `public class MainActivity extends FlutterActivity {` and add the imports before that line.

Did you modify your class signature? If so, can you post the line?

Thanks for the report.

**Comment by reducedcarpet** [comment]
Oh yah, I did: 

public class MainActivity extends FlutterFragmentActivity {

I have totes forgot why I had to extend the fragment activity, but it's necessary for another package I am using. On the plus side, your native splashscreen works fine with flutter fragment activity.

**Comment by henriquearthur** [comment]
Fixed in **v0.1.7** (194591bacd1da82a7f8a876464080b226f432db9):
```
dev_dependencies:
  flutter_native_splash: ^0.1.7
```

---

The package looks now only for `public class MainActivity extends`, which makes it work with custom signatures.

**Comment by SimonIT** [comment]
I had the same problem with missing imports.
Is it possible that kotlin made it not work?

This is line for the class:
`class MainActivity : FlutterActivity() {`

**Comment by henriquearthur** [comment]
> I had the same problem with missing imports.
> Is it possible that kotlin made it not work?
> 
> This is line for the class:
> `class MainActivity : FlutterActivity() {`

Related to #39 

Since recent versions of Flutter changed the default content of MainActivity this package can't find the proper line to use as reference.
