### ISSUE TITLE
Part of the screen is missing when you set android_disable_fullscreen to true, in recent app overview.

### ISSUE THREAD

**Issue by basashi-G** [henriquearthur/flutter_native_splash#73]
Like tihs. 

![Screenshot_1591255397](https://user-images.githubusercontent.com/53048311/83727627-575da100-a680-11ea-903e-5720964666c8.png)

**Comment by serdargu** [comment]
Go to "android/app/main/res/values/styles.xml" file on your project and change the line 
`<item name="android:windowFullscreen">true</item>`
as
`<item name="android:windowFullscreen">false</item>`

**Comment by jonbhanson** [comment]
Should be resolved by 48981828e831768c4ad89a35475e8f9f24e0aca5.
