### ISSUE TITLE
以前设置过闪屏页，使用插件后报错：CantFindMainActivityPath

### ISSUE THREAD

**Issue by Witcher-jufei** [henriquearthur/flutter_native_splash#74]
之前没有用过插件，现在想换成插件来更改闪屏页。该改动的都改了，出现CantFindMainActivityPath错误。报错信息：
Unhandled exception:
*** ERROR [flutter_native_splash] ***
CantFindMainActivityPath
Not able to determinate MainActivity path. Maybe the problem is your package path OR your AndroidManifest.xml 'package' attribute on manifest.

**Comment by shr1k4nt** [comment]
This will happen if the package folders are different than your package name mentioned in the AndroidManifest.xml. This can be fixed by correcting the package folder as per the package name.

**Comment by mjmon** [comment]
> This will happen if the package folders are different than your package name mentioned in the AndroidManifest.xml. This can be fixed by correcting the package folder as per the package name.

this one fixed my issue. thanks

**Comment by adamsmaka** [comment]
I've got the same problem, how did you fix it? Changing package name to be consistent with folder didn't solve the problem to me.

**Comment by jonbhanson** [comment]
Should be resolved by 48981828e831768c4ad89a35475e8f9f24e0aca5.
