### ISSUE TITLE
Plugin CLI not working on android

### ISSUE THREAD

**Issue by charlesarchibong** [henriquearthur/flutter_native_splash#77]
`` 
Unhandled exception:
*** ERROR [flutter_native_splash] ***
CantFindMainActivityPath
Not able to determinate MainActivity path. Maybe the problem is your package path OR your AndroidManifest.xml 'package' attribute on manifest.
#0      _javaOrKotlin (package:flutter_native_splash/android.dart:335:5)
<asynchronous suspension>
#1      _applyMainActivityUpdate (package:flutter_native_splash/android.dart:308:33)
#2      createSplash (package:flutter_native_splash/android.dart:42:9)
<asynchronous suspension>
#3      createSplash (package:flutter_native_splash/flutter_native_splash.dart:20:11)
<asynchronous suspension>
#4      main (file:///home/charlesarchibong/Android/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.1.9/bin/create.dart:5:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
``

**Comment by AhsanAyaz** [comment]
Just faced the same issue.

**Comment by raphagodoi** [comment]
Same here

**Comment by charlesarchibong** [comment]
Check you the path to .Application.kt/java in your app mannifest.

**Comment by tsahnar** [comment]
Same here. Getting the same error

**Comment by mohamdaoui** [comment]
I did some diving into the codebase, and found how the code tries to find the MainActivity based on the package name, in my case, I had changed the package name after creating the project, which resulted in the MainActivity path mismatching the package name.
What I did was manually creating the new path based on my package name, and putting my MainActivity in there.
i.e: My Package in the manifest was: `com.example.test`, but my MainActivity was still under `android/app/src/main/kotlin/com/old/test/MainActivity.kt`, All I had to do was put my MainActivity into a new path that corresponds to the package name, renaming `old` to `example` in this case (same goes for `../java/..`)

**Comment by rydmike** [comment]
Same issue here

**Comment by craftgear** [comment]
I've just encountered this.

What I did to solve this is:

1. check `android/app/src/main/AndroidManifest.xml` line:2 `package` attribute.
2. rename `android/app/src/main/kotlin/com/example/hoge` directories following the package attribute.

For example, if your package attribute is `net.foo.app_name` then rename kotlin dirs like so: ` android/app/src/main/kotlin/net/foo/app_name`.

After this, re run `flutter pub run flutter_native_splash:create`.

**Comment by AdnanKazi** [comment]
> I did some diving into the codebase, and found how the code tries to find the MainActivity based on the package name, in my case, I had changed the package name after creating the project, which resulted in the MainActivity path mismatching the package name.
> What I did was manually creating the new path based on my package name, and putting my MainActivity in there.
> i.e: My Package in the manifest was: `com.example.test`, but my MainActivity was still under `android/app/src/main/kotlin/com/old/test/MainActivity.kt`, All I had to do was put my MainActivity into a new path that corresponds to the package name, renaming `old` to `example` in this case (same goes for `../java/..`)

Great Job it helped me

**Comment by jonbhanson** [comment]
Should be resolved by 48981828e831768c4ad89a35475e8f9f24e0aca5.
