### ISSUE TITLE
Plugin added windowFullscreen to styles.xml

### ISSUE THREAD

**Issue by fedotxxl** [henriquearthur/flutter_native_splash#78]
This plugin added a full-screen style to my app which was a great surprise for me and required half an hour to investigate this problem. This is not expected behavior.  Please make it optional and disabled by default or add a note to description

**Comment by markturnip** [comment]
See #67 #72

**Comment by amatkivskiy** [comment]
Hi all, 

Is there any way to make only a splash screen in fullscreen, not all Flutter app?

**Comment by jonbhanson** [comment]
Should be resolved by 48981828e831768c4ad89a35475e8f9f24e0aca5.
