### ISSUE TITLE
 flutter pub pub run flutter_native_splash: create Could not find .dart in package flutter_native_splash.

### ISSUE THREAD

**Issue by umairmaher44** [henriquearthur/flutter_native_splash#81]
when i run this command  (flutter pub pub run flutter_native_splash: create) it shows this error (Could not find .dart in package flutter_native_splash.).......[
![Screenshot 2020-08-13 at 11 14 18 PM](https://user-images.githubusercontent.com/63322711/90171370-d545d300-ddba-11ea-9ba3-2eca37416d16.png)
![Screenshot 2020-08-13 at 11 14 35 PM](https://user-images.githubusercontent.com/63322711/90171384-db3bb400-ddba-11ea-96b4-84ff40eb9528.png)

](url)

**Comment by nerder** [comment]
You should remove the space between `flutter_native_splash:` and `create`.|

The right command is this one: `flutter pub pub run flutter_native_splash:create`

**Comment by mayankdedhia** [comment]
Seems to be the exact same problem I had, worked with solution with @nerder gave

**Comment by jonbhanson** [comment]
Thanks for the help resolving this issue @nerder .
