### ISSUE TITLE
How to remove/uninstall the splash screen from my app?

### ISSUE THREAD

**Issue by Sultanic** [henriquearthur/flutter_native_splash#82]
Is there an equivalent for `flutter pub pub run flutter_native_splash:create` but `remove`?

If not, and I have to do it manually. I would appreciate detailed steps. Thanks.

**Comment by abdulllrashid** [comment]
For android, Your can goto app/src/main/res/drawable/launch_background.xml and comment on the following lines

` <item>
        <bitmap android:gravity="center" android:src="@drawable/splash" />
    </item>`

You can remove images named splash.png from drawable files to reduce the file size

**Comment by jonbhanson** [comment]
Follow [97](https://github.com/henriquearthur/flutter_native_splash/issues/97) for resolution.
