### ISSUE TITLE
[Feature]splash time

### ISSUE THREAD

**Issue by shinriyo** [henriquearthur/flutter_native_splash#84]
Can you?

https://stackoverflow.com/questions/5618163/displaying-splash-screen-for-longer-than-default-seconds

@henriquearthur

**Comment by shinriyo** [comment]
https://github.com/henriquearthur/flutter_native_splash/issues/10

Deprecated but not add the feature yet.

**Comment by M123-dev** [comment]
This is most likely not implemented in this plugin. Here only the native code in the flutter app is overwritten, which changes what is displayed when initializing the app, even before flutter does anything. If you want to extend the timer, you have to switch to a plugin which is executed at the sttart of Flutter. So a plugin not a dev dependency. For example [this one](https://pub.dev/packages/animated_splash).

**Comment by jonbhanson** [comment]
Right on, @M123-dev 👍🏻
