### ISSUE TITLE
[Feature] Don't search for MainActivity if set to io.flutter.embedding.android.FlutterActivity

### ISSUE THREAD

**Issue by hofbi** [henriquearthur/flutter_native_splash#88]
In https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects (1a) it is explained:

> Since the body of the MainActivity is now empty, you can also optionally delete the MainActivity.java/kt file if you'd like. If you do, you need to change your AndroidManifest.xml's reference to .MainActivity to io.flutter.embedding.android.FlutterActivity.

This means when setting the MainActivity name to `io.flutter.embedding.android.FlutterActivity`, there does not have to be a MainActivity file.

**Current behavior:**

Same error as in #77 

**Expected behavior:**

Ignore MainActivity

**Comment by jonbhanson** [comment]
48981828e831768c4ad89a35475e8f9f24e0aca5 now ignores MainActivity.
