### ISSUE TITLE
Image fades in on iOS

### ISSUE THREAD

**Issue by Vardiak** [henriquearthur/flutter_native_splash#90]
Hello,
I'm not sure if I'm doing something wrong, it seems that with this plugin, the image doesn't show up at first frame on iOS, and then fades in. This is not the same behavior as apps like Twitter or Spotify, where the icon appears instantly. I've been searching a solution by editing the LaunchScreen.storyboard file without success.
Do you have any idea how to recreate this?

**Comment by AntonyLeons** [comment]
I also have this issue, it also goes too fast because of this

**Comment by Vardiak** [comment]
> I also have this issue, it also goes too fast because of this

I fixed the issue... by rebooting my iPhone. This is very weird, Apple doesn't seem to handle launch screens very well.
