### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by asduhauisdhbcuasudhu** [henriquearthur/flutter_native_splash#91]
Is this project still maintained?
It's been almost 8 months since the last commit.
Quite many people seem to be interested in this so it's a pity that its not developed further.
Should we try to find a new maintainer? What are your thoughts?

**Comment by ycherniavskyi** [comment]
I as see it is not ☹️. Has anyone found some alternative?

**Comment by M123-dev** [comment]
Today and the last few days there was a bit of activity, I hope it continues to behave this way

**Comment by jonbhanson** [comment]
Hey everyone.  I've taken over development, and hope to keep this a useful and up-to-date project.  Please flag the issues that are most important with an emoji, and I will work through stuff as I have time.  Merge requests are welcome.
