### ISSUE TITLE
windowFullscreen error

### ISSUE THREAD

**Issue by p02diada** [henriquearthur/flutter_native_splash#92]
Hi, after using this package I get some errors in scroll resize when keyboard appears and I discovered this is due to the windowFullscreen variable set to True.

![ezgif-7-cc6bc20e3597](https://user-images.githubusercontent.com/6508269/94173704-995f5c80-fe94-11ea-85ee-5964973849c7.gif)

**Comment by imadhussain** [comment]
same issue

**Comment by X-SLAYER** [comment]
remove `<item name="android:windowFullscreen">true</item>` from `android\app\src\main\res\values\styles.xml`

**Comment by jonbhanson** [comment]
Should be resolved by 48981828e831768c4ad89a35475e8f9f24e0aca5.
