### ISSUE TITLE
Black screen between the splash screen & the app on iOS

### ISSUE THREAD

**Issue by zzterrozz** [henriquearthur/flutter_native_splash#94]
Same as [issue #54](https://github.com/henriquearthur/flutter_native_splash/issues/54#issue-562104115) but for iOS, I have a black screen between the splash screen & the app.
 
Tested on iOS emulator & physical device.

Any help please ?

**Comment by danielwalczak** [comment]
how did you solve the issue ?

**Comment by zzterrozz** [comment]
A missing Scaffold backgroundColor in one a the screen that was showed by flutter_bloc during the authentication.
I would recommend to use a Future.delayed before the RunApp in order to identify if the black screen is actually created because of the splash screen or the app itself

**Comment by drugsloveyou** [comment]
Did you solve this issue?
